oe_link_lists.link_list_type.*:
  type: config_entity
  label: 'Link List type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    configurable_link_source_plugins:
      type: boolean
      label: 'Whether this bundle should allow to select link source plugins'
    default_link_source:
      type: string
      label: 'Whether this bundle works with only one link source, automatically configured on it'

field.value.link_list_configuration:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value

# The view_mode block setting was removed from core block schema definition.
# See: https://www.drupal.org/project/drupal/issues/3379725
# @see \Drupal\oe_link_lists\Plugin\Block\LinkListBlock
# @see \Drupal\oe_link_lists\Plugin\Derivative\LinkListBlock
block.settings.oe_link_list_block:*:
  type: block_settings
  label: 'Link List'
  constraints:
    FullyValidatable: ~
  mapping:
    view_mode:
      type: string
      label: 'View mode'
      constraints:
        ConfigExists:
          prefix: core.entity_view_mode.oe_link_list_block.
