<?php

/**
 * @file
 * OE link lists local module file.
 */

declare(strict_types=1);

use Drupal\content_moderation\Hook\ContentModerationHooks;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\SelectInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Session\AccountInterface;
use Drupal\field\FieldConfigInterface;
use Drupal\oe_link_lists\Entity\LinkListInterface;
use Drupal\oe_link_lists_local\Form\LinkListInlineForm;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_base_field_info().
 *
 * Adding a boolean field on the link list entity to denote it should not be
 * anywhere reused but only used in the context of the entity that created it
 * as a reference.
 */
function oe_link_lists_local_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'link_list') {
    $fields['local'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Local'))
      ->setDescription(t('Whether the link list is local to another entity.'))
      ->setDefaultValue(FALSE);
  }

  return $fields;
}

/**
 * Implements hook_entity_type_build().
 */
function oe_link_lists_local_entity_type_build(array &$entity_types) {
  /** @var Drupal\Core\Entity\EntityTypeInterface $link_list */
  $link_list = $entity_types['link_list'];
  $link_list->setHandlerClass('inline_form', LinkListInlineForm::class);
}

/**
 * Implements hook_entity_query_alter().
 */
function oe_link_lists_local_query_entity_query_link_list_alter(SelectInterface $query) {
  // For link lists that are marked as local, we don't want them findable in
  // any query made against the link list entities. There are two exceptions to
  // this, as seen below.
  $definition = \Drupal::entityTypeManager()->getDefinition('link_list');
  $data_table = $definition->getDataTable();
  $conditions = $query->conditions();

  if ($query->hasTag('entity_reference')) {
    // If the query is given by the entity reference it can be there for
    // validating a reference, made even with IEF. So in this case we should
    // not kill the query. And we know this by checking for a condition by IDs.
    foreach (Element::children($conditions) as $child) {
      $condition = $conditions[$child];
      if ($condition['field'] === "$data_table.id") {
        return;
      }
    }
  }

  if ($query->getMetaData('all_revisions')) {
    // If the query is made to load revisions and we have a filter by the
    // actual link list ID, we also want to allow. This can be used,
    // for example, by the content moderation system. And unfortunately, did
    // not manage to find a good way to override the moderation handler to
    // prevent local link lists from being moderated.
    foreach (Element::children($conditions) as $child) {
      $condition = $conditions[$child];
      if ($condition['field'] === "$data_table.id") {
        return;
      }
    }
  }

  if ($query->hasTag('allow_local_link_lists')) {
    // We need to be able to query in certain places, such as tests, for all
    // the local link lists so we allow the use of a tag to bypass this
    // condition.
    return;
  }

  $tables = $query->getTables();
  if (!isset($tables[$data_table])) {
    $query->join($data_table, $data_table, "$data_table.id = base_table.id");
  }

  $condition = $query->orConditionGroup();
  $condition->isNull('local');
  $condition->condition('local', 0);
  $query->condition($condition);
}

/**
 * Implements hook_views_query_alter().
 */
function oe_link_lists_local_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $base_entity_type = $view->getBaseEntityType();
  if (!$base_entity_type) {
    return;
  }
  if ($base_entity_type->id() !== 'link_list') {
    return;
  }

  if (!$query->getTableInfo('link_list_field_data')) {
    // The local column is only on the default link list table. So it doesn't
    // exist on the revisions table so we need to check for this.
    return;
  }
  $condition = $query->query()->getConnection()->condition('OR');
  $condition->isNull('local');
  $condition->condition('local', 0);
  $query->addWhere(0, $condition);
}

/**
 * Implements hook_query_alter().
 *
 * Altering the tagged query for when link lists are being loaded and a
 * database query is being used. We don't want local link lists to be
 * queryable.
 */
function oe_link_lists_local_query_link_list_load_multiple_alter(AlterableInterface $query) {
  $conditions = $query->conditions();
  if (!empty(Element::children($conditions))) {
    // If there are conditions, it means the query has specific IDs passed to
    // load, in which case we don't want interfere.
    return;
  }

  $tables = $query->getTables();
  if (isset($tables['revision']['arguments'][':revisionIds[]']) && !empty($tables['revision']['arguments'][':revisionIds[]'])) {
    // It means the query is used to load a specific revision to a join onto
    // the revision table on the requested revision ID.
    return;
  }

  // If there are no conditions it means the loadMultiple() is being used
  // without any IDs in which case we want to filter out the local link lists.
  // We do want to allow the actual loading of a given link list ID.
  $definition = \Drupal::entityTypeManager()->getDefinition('link_list');
  $data_table = $definition->getDataTable();

  if (!isset($tables[$data_table])) {
    $query->join($data_table, $data_table, "$data_table.id = base.id");
  }

  $condition = $query->orConditionGroup();
  $condition->isNull('local');
  $condition->condition('local', 0);
  $query->condition($condition);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add the option to mark link list entity reference fields as local.
 */
function oe_link_lists_local_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state): void {
  /** @var \Drupal\field\FieldConfigInterface $field_config */
  $field_config = $form_state->getFormObject()->getEntity();
  $applicable_field_types = ['entity_reference', 'entity_reference_revisions'];
  if (!in_array($field_config->getType(), $applicable_field_types)) {
    return;
  }

  if ($field_config->getSetting('handler') !== 'default:link_list') {
    return;
  }

  $form['local'] = [
    '#type' => 'checkbox',
    '#title' => t('Local field'),
    '#description' => t('Local link list are link lists marked to only be visible in the context of this reference.'),
    '#default_value' => $field_config->getThirdPartySetting('oe_link_lists_local', 'local') ?? FALSE,
  ];

  $form['#entity_builders'][] = 'oe_link_lists_local_form_field_config_form_builder';
}

/**
 * Entity form builder for the field_config form.
 *
 * Saves the local field settings into the field config settings.
 *
 * @param string $entity_type
 *   The name of the entity type.
 * @param \Drupal\field\FieldConfigInterface $field_config
 *   The field config.
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function oe_link_lists_local_form_field_config_form_builder(string $entity_type, FieldConfigInterface $field_config, array &$form, FormStateInterface $form_state): void {
  $field_config->setThirdPartySetting('oe_link_lists_local', 'local', $form_state->getValue('local'));
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 *
 * Replace the admin title with the actual title if set on the local link list
 * inline entity form tables.
 *
 * Only the alter hook provides us the needed context to be able to determine
 * if the field is local and this is the reason why this didn't go directly
 * in the LinkListInlineForm handler.
 */
function oe_link_lists_local_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['entity_type'] !== 'link_list') {
    return;
  }

  $entity_type = $context['parent_entity_type'];
  $bundle = $context['parent_bundle'];
  $field_name = $context['field_name'];
  $field_definitions = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity_type, $bundle);
  $field_definition = $field_definitions[$field_name];

  if (!LinkListInlineForm::isFieldLocal($field_definition)) {
    return;
  }

  unset($fields['label']);
  $fields['title'] = [
    'type' => 'callback',
    'label' => t('Title'),
    'callback' => '_oe_link_lists_local_inline_entity_form_title_callback',
  ];

}

/**
 * Callback to generate the title of a given link list in a IEF table.
 *
 * @param \Drupal\oe_link_lists\Entity\LinkListInterface $link_list
 *   The link list.
 *
 * @see oe_link_lists_local_inline_entity_form_table_fields_alter()
 *
 * @return array
 *   The title.
 */
function _oe_link_lists_local_inline_entity_form_title_callback(LinkListInterface $link_list): array {
  $title = $link_list->getTitle() ?? t('- No title -');
  return [
    '#markup' => $title,
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Whenever a BaseFieldOverride entity is saved, we include the local setting
 * into the exported third party settings if relevant.
 */
function oe_link_lists_local_base_field_override_presave(EntityInterface $entity) {
  /** @var \Drupal\Core\Field\Entity\BaseFieldOverride $entity */
  $settings = $entity->getItemDefinition()->getSetting('oe_link_lists_local');
  if (!$settings) {
    return;
  }

  if ($entity->getItemDefinition()->getSetting('target_type') !== 'link_list') {
    return;
  }

  foreach ($settings as $setting => $value) {
    $entity->setThirdPartySetting('oe_link_lists_local', $setting, $value);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * When we save a local link list, check to see if it has the moderation state
 * field and automatically set it to the published state as well as mark the
 * entity as published.
 */
function oe_link_lists_local_link_list_presave(LinkListInterface $link_list) {
  if (!$link_list->hasField('moderation_state') || !(bool) $link_list->get('local')->value) {
    return;
  }

  if ($link_list->isPublished()) {
    // If the link list is already published, we don't need to do anything
    // anymore.
    return;
  }

  $link_list->setPublished();

  $workflow = \Drupal::service('content_moderation.moderation_information')->getWorkflowForEntity($link_list);
  foreach ($workflow->get('type_settings')['states'] as $state => $state_info) {
    if ($state_info['published'] === TRUE) {
      $link_list->set('moderation_state', $state);
      break;
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function oe_link_lists_local_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'entity_access' && isset($implementations['content_moderation'])) {
    // If the site is using content_moderation, remove the implementation and
    // rely on the one from this submodule.
    // @see oe_link_lists_local_entity_access().
    unset($implementations['content_moderation']);
  }
}

/**
 * Implements hook_entity_access().
 *
 * Does almost nothing except prevents content_moderation_entity_access() from
 * running (if it exists) in case the entity is a local link list. This is
 * because we don't want local link list access to be tied to the workflow.
 * I tried to override the moderation handler but could not do it due to it
 * (and other handlers) being overridden by other modules as well.
 */
function oe_link_lists_local_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity instanceof LinkListInterface && (bool) $entity->get('local')->value) {
    return AccessResult::neutral();
  }

  if (function_exists('content_moderation_entity_access')) {
    // For Drupal 10, execute the hook function directly.
    return content_moderation_entity_access($entity, $operation, $account);
  }
  elseif (class_exists(ContentModerationHooks::class)) {
    // For Drupal 11, use the class that contains the hook implementations.
    // Invoking the hook is not possible, since it is disabled.
    // @see oe_link_lists_local_module_implements_alter()
    $content_moderation_hooks = new ContentModerationHooks();
    return $content_moderation_hooks->entityAccess($entity, $operation, $account);
  }

  return AccessResult::neutral();
}
